name: Creaating frist CI and CD flow on github
on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test






