name: Creating first CI and CD flow on GitHub

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        run: |
          echo "Using the already checked-out repository provided by GitHub Actions"
          ls -al
          ls -al ./app # Verify contents of the subdirectory

      - name: Set up Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Run tests
        working-directory: ./app
        run: npm test
